### ISSUE TITLE
tensorflow dataset returns error for mlflow

### ISSUE THREAD

**Issue by aliabdoli** [Galileo-Galilei/kedro-mlflow#236] opened 2021-09-03 09:54 UTC
## Description
Hi there and thanks for this amazing package/repo.

It seems when tensorflow.keras model is trained and stored as part of training, it cant be properly used in mlflow prediction 

## Context

- tensorflow keras model trained and stored in catalog.yml
my catalog.yml
```
encoder_model:
  type: kedro.extras.datasets.tensorflow.TensorFlowModelDataset
  filepath: C:/database/moosir/rnn/data/06_models/model_encoder.h5
  save_args:
    save_format: "h5"
    overwrite: True
    include_optimizer: True
    save_traces: True
```

- I can successfully run `kedro run --pipeline inference`
- however when I run it through an ml flow client in python code, i gets error
my client code
```

    RUN_ID = "dc8b93a4304d43acbc3bb44009d078e4"
    package_name ="rnn"

    with KedroSession.create(package_name, env=None, extra_params={}) as session:
        local_context = session

        mlflow_config = get_mlflow_config()
        mlflow_config.setup(local_context)

        instances = pd.read_csv("data.csv", index_col="Timestamp", parse_dates=True)
        model = load_model(f"runs:/{RUN_ID}/rnn_model")

        predictions = model.predict(instances)

```
the error I get
```
2021-09-03 19:44:41,813 - kedro.runner.sequential_runner - WARNING - There are 1 nodes that have not run.
You can resume the pipeline run by adding the following argument to your previous command:
  --from-nodes "predict_bidirectional_lstm([encoder_model,x_lstm]) -> [x_encoded]"
2021-09-03 19:44:41,823 - kedro.framework.session.store - INFO - `save()` not implemented for `BaseSessionStore`. Skipping the step.
Traceback (most recent call last):
  File "C:/code/my_code/Trader.Forex.Moosir/src/rnn/pipeline_kedro/user_client.py", line 39, in <module>
    run()
  File "C:/code/my_code/Trader.Forex.Moosir/src/rnn/pipeline_kedro/user_client.py", line 25, in run
    predictions = model.predict(instances)
  File "C:\Users\ali\anaconda3\envs\moosir-rnn-research\lib\site-packages\mlflow\pyfunc\__init__.py", line 608, in predict
    return self._model_impl.predict(data)
  File "C:\Users\ali\anaconda3\envs\moosir-rnn-research\lib\site-packages\mlflow\pyfunc\model.py", line 296, in predict
    return self.python_model.predict(self.context, model_input)
  File "C:\Users\ali\anaconda3\envs\moosir-rnn-research\lib\site-packages\kedro_mlflow\mlflow\kedro_pipeline_model.py", line 131, in predict
    pipeline=self.pipeline_ml.inference, catalog=self.loaded_catalog
  File "C:\Users\ali\anaconda3\envs\moosir-rnn-research\lib\site-packages\kedro\runner\runner.py", line 106, in run
    self._run(pipeline, catalog, run_id)
  File "C:\Users\ali\anaconda3\envs\moosir-rnn-research\lib\site-packages\kedro\runner\sequential_runner.py", line 90, in _run
    run_node(node, catalog, self._is_async, run_id)
  File "C:\Users\ali\anaconda3\envs\moosir-rnn-research\lib\site-packages\kedro\runner\runner.py", line 218, in run_node
    node = _run_node_sequential(node, catalog, run_id)
  File "C:\Users\ali\anaconda3\envs\moosir-rnn-research\lib\site-packages\kedro\runner\runner.py", line 307, in _run_node_sequential
    outputs = _call_node_run(node, catalog, inputs, is_async, run_id=run_id)
  File "C:\Users\ali\anaconda3\envs\moosir-rnn-research\lib\site-packages\kedro\runner\runner.py", line 275, in _call_node_run
    raise exc
  File "C:\Users\ali\anaconda3\envs\moosir-rnn-research\lib\site-packages\kedro\runner\runner.py", line 265, in _call_node_run
    outputs = node.run(inputs)
  File "C:\Users\ali\anaconda3\envs\moosir-rnn-research\lib\site-packages\kedro\pipeline\node.py", line 466, in run
    raise exc
  File "C:\Users\ali\anaconda3\envs\moosir-rnn-research\lib\site-packages\kedro\pipeline\node.py", line 459, in run
    outputs = self._run_with_dict(inputs, self._inputs)
  File "C:\Users\ali\anaconda3\envs\moosir-rnn-research\lib\site-packages\kedro\pipeline\node.py", line 520, in _run_with_dict
    return self._decorated_func(**kwargs)
  File "C:\code\my_code\Trader.Forex.Moosir\src\rnn\pipeline_kedro\src\rnn\pipelines\ml_app\nodes\encoder_training.py", line 77, in predict_bidirectional_lstm
    encoded_result = encoder_model.predict(x_input)
  File "C:\Users\ali\anaconda3\envs\moosir-rnn-research\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1727, in predict
    tmp_batch_outputs = self.predict_function(iterator)
  File "C:\Users\ali\anaconda3\envs\moosir-rnn-research\lib\site-packages\tensorflow\python\eager\def_function.py", line 889, in __call__
    result = self._call(*args, **kwds)
  File "C:\Users\ali\anaconda3\envs\moosir-rnn-research\lib\site-packages\tensorflow\python\eager\def_function.py", line 933, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "C:\Users\ali\anaconda3\envs\moosir-rnn-research\lib\site-packages\tensorflow\python\eager\def_function.py", line 764, in _initialize
    *args, **kwds))
  File "C:\Users\ali\anaconda3\envs\moosir-rnn-research\lib\site-packages\tensorflow\python\eager\function.py", line 3050, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "C:\Users\ali\anaconda3\envs\moosir-rnn-research\lib\site-packages\tensorflow\python\eager\function.py", line 3444, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "C:\Users\ali\anaconda3\envs\moosir-rnn-research\lib\site-packages\tensorflow\python\eager\function.py", line 3289, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "C:\Users\ali\anaconda3\envs\moosir-rnn-research\lib\site-packages\tensorflow\python\framework\func_graph.py", line 999, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "C:\Users\ali\anaconda3\envs\moosir-rnn-research\lib\site-packages\tensorflow\python\eager\def_function.py", line 672, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "C:\Users\ali\anaconda3\envs\moosir-rnn-research\lib\site-packages\tensorflow\python\framework\func_graph.py", line 986, in wrapper
    raise e.ag_error_metadata.to_exception(e)
AssertionError: in user code:

    C:\Users\ali\anaconda3\envs\moosir-rnn-research\lib\site-packages\tensorflow\python\keras\engine\training.py:1569 predict_function  *
        return step_function(self, iterator)
    C:\Users\ali\anaconda3\envs\moosir-rnn-research\lib\site-packages\tensorflow\python\keras\engine\training.py:1559 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    C:\Users\ali\anaconda3\envs\moosir-rnn-research\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:1285 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    C:\Users\ali\anaconda3\envs\moosir-rnn-research\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2833 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    C:\Users\ali\anaconda3\envs\moosir-rnn-research\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:3608 _call_for_each_replica
        return fn(*args, **kwargs)
    C:\Users\ali\anaconda3\envs\moosir-rnn-research\lib\site-packages\tensorflow\python\keras\engine\training.py:1552 run_step  **
        outputs = model.predict_step(data)
    C:\Users\ali\anaconda3\envs\moosir-rnn-research\lib\site-packages\tensorflow\python\keras\engine\training.py:1525 predict_step
        return self(x, training=False)
    C:\Users\ali\anaconda3\envs\moosir-rnn-research\lib\site-packages\tensorflow\python\keras\engine\base_layer.py:1030 __call__
        outputs = call_fn(inputs, *args, **kwargs)
    C:\Users\ali\anaconda3\envs\moosir-rnn-research\lib\site-packages\tensorflow\python\keras\engine\functional.py:421 call
        inputs, training=training, mask=mask)
    C:\Users\ali\anaconda3\envs\moosir-rnn-research\lib\site-packages\tensorflow\python\keras\engine\functional.py:565 _run_internal_graph
        assert x_id in tensor_dict, 'Could not compute output ' + str(x)

    AssertionError: Could not compute output KerasTensor(type_spec=TensorSpec(shape=(None, 32), dtype=tf.float32, name=None), name='bidirectional/forward_encoder_1/PartitionedCall:2', description="created by layer 'bidirectional'")


```

## Steps to Reproduce
- mentioned above
## Expected Result
I think the problem is deepcopy to MemoryDataSet that happens for TensorflowDataSet (which should not happen, need to be `copy-assign` I believe).
- problem in code in git: https://github.com/Galileo-Galilei/kedro-mlflow/blob/58f0d9449e8cd3cc26a59c157a16f71b454bec2e/kedro_mlflow/mlflow/kedro_pipeline_model.py#L119

cos before the line I mentioned above I can run predict on my model, but after saving it, (which save successfully) but it changes something in the model that make it useless (I think it messes up with the graphs)
also, it is a known issue that tensorflow cannt be easily pickled ([here](https://stackoverflow.com/questions/63730066/how-to-use-tf-data-dataset-with-kedro)), that s probably why the came up with `TensorFlowModelDataset`

## Your Environment
- windows 10, 64
- conda
- here is my environment.yml
```
dependencies:
  - python=3.7
  - ta-lib
  - numpy
  - pandas
  - matplotlib=3.2.2
  - graphviz
  - seaborn
  - cudatoolkit=11.2
  - cudnn=8.1
  - pip
  - pip:
    - kedro-mlflow
    - black==21.5b1
    - flake8>=3.7.9, <4.0
    - ipython==7.10
    - isort~=5.0
    - jupyter~=1.0
    - jupyter_client>=5.1, <7.0
    - jupyterlab~=3.0
    - kedro==0.17.4
    - kedro-telemetry~=0.1.0
    - nbstripout~=0.4
    - pytest-cov~=2.5
    - pytest-mock>=1.7.1, <2.0
    - pytest~=6.2
    - wheel>=0.35, <0.37
    - sklearn
    - tensorflow-gpu==2.5.0
    - kedro-viz
```
#

**Comment by Galileo-Galilei** [comment] 2021-09-03 18:11
Hi, 

just to be clear, you are using the ``pipeline_ml_factory`` in your ``hooks.py`` (for version 0.16.x) or your ``pipeline_registry.py`` (for version 0.17.x), and you have a model which is your entire inference pipeline, not just your tensorflow one?

If the problem is just due to deepcopying the model as you suspect (and I think so too), you can specify the ``copy_mode`` argument in your ``pipeline_ml_factory`` call, e.g:

replace this:

https://github.com/Galileo-Galilei/kedro-mlflow-tutorial/blob/4c85c357162a85093f0875fe3085fbd9ebe2e4be/src/kedro_mlflow_tutorial/hooks.py#L60-L70

with : 

```python
training_pipeline_ml = pipeline_ml_factory(
            training=ml_pipeline.only_nodes_with_tags("training"),
            inference=inference_pipeline,
            input_name="instances",
            model_name="kedro_mlflow_tutorial",
            conda_env={
                "python": 3.7,
                "pip": [f"kedro_mlflow_tutorial=={PROJECT_VERSION}"],
            },
            model_signature="auto",
            copy_mode={"encoder_model": "assign"}  # new line to assign
)
```
 In this case, you can see that the loaded catalog uses the proper ``copy_mode`` and it should be ok.

https://github.com/Galileo-Galilei/kedro-mlflow/blob/58f0d9449e8cd3cc26a59c157a16f71b454bec2e/kedro_mlflow/mlflow/kedro_pipeline_model.py#L54-L59

If this does not solve your problem, can you share an example repo (or at least share the code of your tensorflow node) so that I can fully reproduce your bug ?

**Comment by aliabdoli** [comment] 2021-09-03 22:41
hi @Galileo-Galilei ,
That was the place I was looking for (to be able to pass on the copy_mode). 
I just followed your suggestion and **it works fine now**
All good and thanks mate.

**Comment by Galileo-Galilei** [comment] 2021-09-04 06:22
Great! I close the issue but feel free to reopen if needed.

**Closed by Galileo-Galilei** 2021-09-04 06:22 UTC
