### ISSUE TITLE
Download mlflow artifact

### ISSUE THREAD

**Issue by Groskilled** [Galileo-Galilei/kedro-mlflow#415] opened 2023-03-08 15:05 UTC
Hi !

I am trying to download csv files from a mlflow run.
I tried everything I could think of, and most of the times I get `Run run_id not found` error.
Here's what I am using

```
dataframe:
  type: kedro_mlflow.io.artifacts.MlflowArtifactDataSet
  data_set:
    type: pandas.CSVDataSet
    filepath: contribution_df.csv
  run_id: run_id
```

I don't know what I am missing. The run_id I am using works juste fine when I use MlflowClient().download_artifacts()

Have a nice day :)

**Comment by Galileo-Galilei** [comment] 2023-03-08 21:23
Hi, sorry to see your facing some issue. This definitely looks like a bug, your configuration should work as is. 

It looks like mlflow has not the right ``mlflow_tracking_uri`` configured. 

Some questions :
- Could you copy paste the exact stacktrace you get with the following code? 
- Do you run it through the CLI or a notebook?
- How is your mmlflow configured? Is it a remote server? What bakend does it use for storage? do you know [which scenario described in their doc](https://mlflow.org/docs/latest/tracking.html#how-runs-and-artifacts-are-recorded) apply to your configuration?

I'll make a couple of try on my side.

**Comment by Groskilled** [comment] 2023-03-09 08:48
Hi.

Here's the stack trace, I removed some informations like the path and the run_id.

```
.../lib/python3.10/site-packages/azure/datalake/store/lib.py:39: DeprecationWarning: 'urllib3.contrib.pyopenssl' module is deprecated and will be removed in a future release of urllib3 2.x. Read more in this issue: https://github.com/urllib3/urllib3/issues/2680
  from requests.packages.urllib3.contrib.pyopenssl import extract_from_urllib3 as enforce_no_py_open_ssl
.../lib/python3.10/site-packages/kedro_mlflow/io/artifacts/mlflow_artifact_dataset.py:118: FutureWarning: ``mlflow.tracking.client.MlflowClient.download_artifacts`` is deprecated since 2.0. This method will be removed in a future release. Use ``mlflow.artifacts.download_artifacts`` instead.
  temp_download_filepath = mlflow_client.download_artifacts(
Traceback (most recent call last):
  File ".../lib/python3.10/site-packages/kedro/io/core.py", line 186, in load
    return self._load()
  File ".../lib/python3.10/site-packages/kedro_mlflow/io/artifacts/mlflow_artifact_dataset.py", line 118, in _load
    temp_download_filepath = mlflow_client.download_artifacts(
  File ".../lib/python3.10/site-packages/mlflow/utils/annotations.py", line 95, in deprecated_func
    return func(*args, **kwargs)
  File ".../lib/python3.10/site-packages/mlflow/tracking/client.py", line 1491, in download_artifacts
    return self._tracking_client.download_artifacts(run_id, path, dst_path)
  File ".../lib/python3.10/site-packages/mlflow/tracking/_tracking_service/client.py", line 475, in download_artifacts
    return self._get_artifact_repo(run_id).download_artifacts(path, dst_path)
  File ".../lib/python3.10/site-packages/mlflow/tracking/_tracking_service/client.py", line 412, in _get_artifact_repo
    run = self.get_run(run_id)
  File ".../lib/python3.10/site-packages/mlflow/tracking/_tracking_service/client.py", line 72, in get_run
    return self.store.get_run(run_id)
  File ".../lib/python3.10/site-packages/mlflow/store/tracking/file_store.py", line 634, in get_run
    run_info = self._get_run_info(run_id)
  File ".../lib/python3.10/site-packages/mlflow/store/tracking/file_store.py", line 657, in _get_run_info
    raise MlflowException(
mlflow.exceptions.MlflowException: Run 'XXX' not found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".../test.py", line 7, in <module>
    contribution_df = catalog.load("dataframe")
  File ".../lib/python3.10/site-packages/kedro/io/data_catalog.py", line 347, in load
    result = dataset.load()
  File ".../lib/python3.10/site-packages/kedro/io/core.py", line 604, in load
    return super().load()
  File ".../lib/python3.10/site-packages/kedro/io/core.py", line 195, in load
    raise DataSetError(message) from exc
kedro.io.core.DataSetError: Failed while loading data from data set MlflowCSVDataSet(filepath=contribution_df.csv, protocol={}, save_args={'index': False}).
Run 'XXX' not found
```

I've tried running it from a jupyter notebook and a python script and get the same error.

About the mlflow configuration, we use azure as the backend, but I am not sure about the scenario, I'll try to get more informations.

If this can help you, here a part of code I use to get the run_id and the files I need.

```
auth = ServicePrincipalAuthentication(
        settings.cfg.TENANT_ID,
        settings.cfg.CLIENT_ID,
        settings.cfg.CLIENT_SECRET,
)
workspace = Workspace(
        subscription_id=settings.cfg.SUBSCRIPTION_ID,
        resource_group=settings.cfg.AML_RESOURCE_GROUP,
        workspace_name=settings.cfg.AML_WORKSPACE_NAME,
        auth=auth,
)
mlflow.set_tracking_uri(workspace.get_mlflow_tracking_uri())
mlflow.set_experiment(experiment)

client = MlflowClient()
client.download_artifacts(run_id, file, file_path)
```

I'll try to get more informations about which scenario apply to our configuration.

Have a nice day :)

**Comment by Galileo-Galilei** [comment] 2023-03-13 20:38
Hi, 

sorry for the radio silence, I had no internet access for the past 4 days. I've try to reproduce your error but unfortunately I don't manage to get an error, it seems to work just fine (I've tried with a local mlflow setup and  a remote one, but not on an azure workspace). 

Just to understand your workflow: 
- the code snippet you give above work well inside a script /  notebook
- when you use the catalog entry above and run ``kedro run``  through the CLI you get the error. 

Some things I'd like to check: 
- can you double check the run_id in your catalog entry? Especially, can you check there is no extra space at the end of the run id? Something like ``run_id:  1234 `` may eventually cause a ``run '1234 ' not found" error because of the extra space
- can you confirm your ``mlflow.yml`` has the same mlflow_tracking_uri than your azure workspace under the ``server.mlflow_tracking_uri`` key? If not, it is likely looking for your run under the mlruns folder instead of your azure workspace which would cause a "run not found" error
- If both are ok, can you check try calling the dataset inside a script and tell me if the error still happens ? You can use the following code snippet:

```python
auth = ServicePrincipalAuthentication(
        settings.cfg.TENANT_ID,
        settings.cfg.CLIENT_ID,
        settings.cfg.CLIENT_SECRET,
)
workspace = Workspace(
        subscription_id=settings.cfg.SUBSCRIPTION_ID,
        resource_group=settings.cfg.AML_RESOURCE_GROUP,
        workspace_name=settings.cfg.AML_WORKSPACE_NAME,
        auth=auth,
)
mlflow.set_tracking_uri(workspace.get_mlflow_tracking_uri())
mlflow.set_experiment(experiment)

from kedro_mlflow.io.artifacts import MlflowArtifactDataSet
mlflow_dataset = MlflowArtifactDataSet(
    data_set=dict(
        type="pandas.CSVDataSet",
        filepath=r"contribution_df.csv",
    ),
    run_id=<RUN_ID>,
)

df=mlflow_dataset.load()
```

**Comment by Groskilled** [comment] 2023-03-16 14:59
Hi,

Sorry for the delay.

So, I've tried running the code inside a python script and inside a notebook and both raise the same error.
I am not using `kedro run` to run the script, just python script.py

Using the code snippet you gave me, it works just fine.

**Comment by Galileo-Galilei** [comment] 2023-03-21 21:32
Actually if you launch the script with ``kedro run`` or open a notebook with ``kedro jupyter notebook`` command, ``kedro-mlflow`` automatically setup the tracking uri. If you launch it with  ``python script.py`` or in a notebook without the kedro context, the mlflow tracking uri is not set automatically, so you need to set it up manually yourself. 

I close the issue, feel free to reopen!

**Closed by Galileo-Galilei** 2023-03-21 21:32 UTC
