### ISSUE TITLE
Missing project path prevents from running a project with kedro-airflow

### ISSUE THREAD

**Issue by mwiewior** [Galileo-Galilei/kedro-mlflow#54] opened 2020-08-24 13:22 UTC
I propose to add project_path to `run.py` template in #53
```Python
        MlflowPipelineHook(
            model_name="{{ cookiecutter.python_package }}", conda_env="{{ cookiecutter.project_path }}/src/requirements.txt",
        ),
```

**Comment by Galileo-Galilei** [comment] 2020-08-27 20:45
Hello,

I am aware of this problem and kedro-airflow specifies that [paths need to be absolute](https://github.com/quantumblacklabs/kedro-airflow#prerequisites). There is always a dilemma between keeping path relative (to make the project work "as is" when pulled) or making path absolute (for more declarative configuration and enhanced consistency). 

I would incline to accept this, but I want to **deprecate `model_name` and `conda_env`  as arguments of MlflowPipelineHook** in a future release because it is much more consistent to pass them as arguments for `pipeline_ml` rather than of a `Hook` and mainly because of #29. If we do this, this argument will no longer be auto-filled and you will have to specify this path manually when creating a `PipelineML` object so it will be up to you to decide whether you want a relative or absolute path.

We have to discuss it with @kaemo, but #29 is a pretty big change and it may not be completed until next release. We may merge your PR even if we expect it to be deprecated on the (short/medium/long?) run.

Let me know if it makes sense to you.

**Comment by Galileo-Galilei** [comment] 2020-09-08 21:36
Juste for the record @mwiewior, I am curious for why this is actually needed:
- If you use `pipeline_ml`, this makes sense but this class is not compatible at all with kedro-airflow plugin (we could give a try to make it more compatible, but is due to airflow not accepting hooks so it will be very hacky and even impossible without collaboration from the kedro team). Just changing the path from relative to absolute will not fix your problem
- If you do not use `pipeline_ml`, this argument was not used so I don't understand what kind of failure you faced. Could you give more detailed information and a reproducible example / error message?

**Comment by Galileo-Galilei** [comment] 2020-10-10 09:34
I close th issue which is fixed in the upcoming realease. Feel free to reopen if you have extra questions / informations.

**Closed** 2020-10-10 09:35 UTC
Labels: need-design-decision, question
