### ISSUE TITLE
Add nodes to disable_tracking conditions

### ISSUE THREAD

**Issue by Yairama** [Galileo-Galilei/kedro-mlflow#491] opened 2023-11-22 20:08 UTC
A way to avoid the error of `exceeded length limit of 500` is adding the pipeline that causes the problem to the mlflow.yml, in the disable_tracking part. [example](https://kedro-mlflow.readthedocs.io/en/stable/source/04_experimentation_tracking/01_configuration.html#deactivate-tracking-under-conditions).

But a better way could be avoid just the problematic node instead all the pipeline. Something like this:

```yml

tracking:
  # You can specify a list of pipeline names for which tracking will be disabled
  # Running "kedro run --pipeline=<pipeline_name>" will not log parameters
  # in a new mlflow run

  disable_tracking:
    pipelines:
      [
       # Some pipelines
      ]
    nodes:
      [
       # Some Nodes
      ] 

```

**Comment by Galileo-Galilei** [comment] 2023-11-23 07:58
Hello, I don't think it is a good idea to ignore a specific node because it hurts reproducibility, it needs to be specified manually each time the parameters is over the limit and removed when it is under the limit, and it tightens the configuration with the pipelines. 

That said, does setting ``server.tracking.params.long_params_strategy= truncate`` fits your needs? It will automatically truncate parameters above the limit so you won't have logging issues.

**Comment by Galileo-Galilei** [comment] 2023-11-23 08:00
Hello, I don't think it is a good idea to ignore a specific node because it hurts reproducibility, it needs to be specified manually each time the parameters is over the limit and removed when it is under the limit, and it tightens the configuration with the pipelines. 

That said, does setting ``server.tracking.params.long_params_strategy= truncate`` fits your needs? It will automatically truncate parameters above the limit so you won't have logging issues.

**Comment by Galileo-Galilei** [comment] 2023-12-19 11:09
Hi, I close the issue as I think above solution is working and better than ignoring a node, feel free to reopen if needed.

**Closed by Galileo-Galilei** 2023-12-19 11:09 UTC
